In [72]:
#1 Print all elements of a list using for loop.


In [73]:
girls= ["Dee", "Ajoke", "Adeola", "Adedoyin", "Lilian", "Patience"]
for x in girls:
    print(x)

Dee
Ajoke
Adeola
Adedoyin
Lilian
Patience


In [74]:
"""2)
Using range(1,101), make two list, one containing all even numbers and
other containing all odd numbers.
"""

' Using range(1,101), make two list, one containing all even numbers and\nother containing all odd numbers.\n'

In [79]:

import numpy as np
np.arange(1,101)

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [76]:
np.arange(1,101,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [77]:
np.arange(0,101,2)

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [78]:
##Take input of age of 3 people by user and determine oldest and youngest among them.

In [85]:
age = int(input("What is your age? "))
if age== 12:
    print("You are the oldest")
elif age< 9 :
    print("You are  the youngest ")


What is your age? 10


In [ ]:
###Write a Python script to merge two Python dictionaries


In [45]:
'''Tech4Dev ={"names": "Kenny", 
           "Adeola","Adenike","Adeola", "Abiola", "Abosede", "Adedoyin",
           "courses": "DataScience", "Web_Dev", "Product_Design", "UIUX","CyberSecurity","Virtual_reality","Graphics"}
           '''

'Tech4Dev ={"names": "Kenny", \n           "Adeola","Adenike","Adeola", "Abiola", "Abosede", "Adedoyin",\n           "courses": "DataScience", "Web_Dev", "Product_Design", "UIUX","CyberSecurity","Virtual_reality","Graphics"}\n           '

In [91]:
Tech4Dev ={"names": "Kenny", 
           "courses": "DataScience"}


Tech4Dev

{'names': 'Kenny', 'courses': 'DataScience'}

In [93]:
colors = {"girls": "Dee"}
colors

{'girls': 'Dee'}

In [97]:
x = Tech4Dev.update(colors)
x

In [108]:
'''A company decided to give bonus of 5% to employee if his/her year of service is more than 5
years. Ask user for their salary and year of service and print the net bonus amount
'''

'A company decided to give bonus of 5% to employee if his/her year of service is more than 5\nyears. Ask user for their salary and year of service and print the net bonus amount\n'

In [ ]:
name = input("What is your name ? ")
salary = int(input("What is your salary ? " + "k" )
x = int(input("How many years of service do you have ? "))
             
if year < 5:
    print("No Bonus")
else:
    print("Your net bonus is 5% " + name)

In [90]:
## Write a Python program to remove a key from a dictionary.

In [68]:
Tech4Dev.pop("courses")

'DataScience'

In [66]:
Tech4Dev


{'glory': 'Kenny'}

In [ ]:


## Write a Python program to get the largest number from a list

In [71]:
num = np.arange(1,100)
num

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [72]:
max(num)

99

In [104]:
#grades

name= input("What is your name ? ") 
gradeScore = int(input("What is Your Score "))

if gradeScore > 80:
    print("Well done, this is an A" + " " + name)
elif gradescore <80 and gradeScore > 60:
    print("You had a B" + " " + name)
elif gradescore < 60 and gradeScore > 50:
    print("You had a C" + " " + name)
elif gradescore < 50 and gradeScore > 45:
    print("You had a D" + " " + name)
elif gradescore <45 and gradeScore > 25:
    print("You had an E" + " " + name)
elif gradescore <25:
    print("You had a F" + " " + name)

What is your name ? Patience
What is Your Score 99
Well done, this is an A Patience
