In [7]:
'''
 20 in built methods in pandas


'''

'\n 20 in built methods on pandas\n\n\n'

In [8]:
import pandas as pd
import numpy as np

In [61]:
df = pd.DataFrame(num)
df

0   1   2   3
0  29  12  42  23
1  25  25  26  26
2  34  28  41  37
3  11  35  49  48
4  42  12  16  27

In [15]:
df = pd.DataFrame(data = num, index = 'A,B,C,D,E'.split(','), columns = 'W,X,Y,Z'.split(','))
df

W   X   Y   Z
A  29  12  42  23
B  25  25  26  26
C  34  28  41  37
D  11  35  49  48
E  42  12  16  27

In [18]:
#1
#It is used to get the first n rows, gives the first 5 by default
df.head(2)

W   X   Y   Z
A  29  12  42  23
B  25  25  26  26

In [20]:
#2
#It is used to get the last n rows, gives the last 5 by default if no number is specified
df.tail()

W   X   Y   Z
A  29  12  42  23
B  25  25  26  26
C  34  28  41  37
D  11  35  49  48
E  42  12  16  27

In [22]:
#3
#Returns description of the data in the DataFrame
df.describe()

W          X         Y          Z
count   5.000000   5.000000   5.00000   5.000000
mean   28.200000  22.400000  34.80000  32.200000
std    11.519549  10.163661  13.44247  10.281051
min    11.000000  12.000000  16.00000  23.000000
25%    25.000000  12.000000  26.00000  26.000000
50%    29.000000  25.000000  41.00000  27.000000
75%    34.000000  28.000000  42.00000  37.000000
max    42.000000  35.000000  49.00000  48.000000

In [24]:
#4
#It is used to index a portion of the DataFrame, used on label, while iloc is integer- based
df.loc['A']

W    29
X    12
Y    42
Z    23
Name: A, dtype: int32

In [26]:
#5
#It is used to remove the specified row or column, by specifying the column axis, (axis='columns') or specifying the row axis, (axis=index)
df.drop('X',axis=1)

W   Y   Z
A  29  42  23
B  25  26  26
C  34  41  37
D  11  49  48
E  42  16  27

In [27]:
#6
#It is used to count unique values
df['W'].value_counts()

29    1
25    1
34    1
11    1
42    1
Name: W, dtype: int64

In [29]:
#7
#Gives the maximum value of each column
df["Z"].max()


48

In [32]:
#8
#Enables us to know the shape of the DataFrame
df.shape

(5, 4)

In [33]:
#9
#Detects  missing values in a column
df.isna().sum()

W    0
X    0
Y    0
Z    0
dtype: int64

In [41]:
#10
#Replaces the null values with a specified value
df.fillna(value = 'd', inplace =True)
df

W   X   Y   Z
A  29  12  42  23
B  25  25  26  26
C  34  28  41  37
D  11  35  49  48
E  42  12  16  27

In [87]:
#11
# Checks whatever the dataframe contains the value
assignment = df.isin([50, 40])

In [73]:
#12
#Returns the mean of the DataFrame
assignment.mean()

34.8

In [74]:
#13
#Returns the standard deviation of the DataFrame
assignment.std()

13.442470011125186

In [75]:
#14
#Returns the minimum value in the DataFrame
assignment.min()

16

In [49]:
#15
#Gives the description of the columns, the count, mean,std, etc  and the transpose writes the columns as rows and the rows and columns
assignment.describe().transpose()

Z          23    26    27    37    48
W count   1.0   1.0   1.0   1.0   1.0
  mean   29.0  25.0  42.0  34.0  11.0
  std     NaN   NaN   NaN   NaN   NaN
  min    29.0  25.0  42.0  34.0  11.0
  25%    29.0  25.0  42.0  34.0  11.0
  50%    29.0  25.0  42.0  34.0  11.0
  75%    29.0  25.0  42.0  34.0  11.0
  max    29.0  25.0  42.0  34.0  11.0
X count   1.0   1.0   1.0   1.0   1.0
  mean   12.0  25.0  12.0  28.0  35.0
  std     NaN   NaN   NaN   NaN   NaN
  min    12.0  25.0  12.0  28.0  35.0
  25%    12.0  25.0  12.0  28.0  35.0
  50%    12.0  25.0  12.0  28.0  35.0
  75%    12.0  25.0  12.0  28.0  35.0
  max    12.0  25.0  12.0  28.0  35.0
Y count   1.0   1.0   1.0   1.0   1.0
  mean   42.0  26.0  16.0  41.0  49.0
  std     NaN   NaN   NaN   NaN   NaN
  min    42.0  26.0  16.0  41.0  49.0
  25%    42.0  26.0  16.0  41.0  49.0
  50%    42.0  26.0  16.0  41.0  49.0
  75%    42.0  26.0  16.0  41.0  49.0
  max    42.0  26.0  16.0  41.0  49.0

In [50]:
#16
#Finds unique value from a series 
df['Y'].unique

<bound method Series.unique of A    42
B    26
C    41
D    49
E    16
Name: Y, dtype: int32>

In [55]:
#17
#Gives the number of unique values
df.Z.value_counts().size

5

In [57]:
#18
#Gives the total memory being used by each column in the dataframe
df.memory_usage()

Index    40
W        20
Z        20
dtype: int64

In [58]:
#19
#used to get percentage
df.pct_change()

W         Z
Y                     
42       NaN       NaN
26 -0.137931  0.130435
41  0.360000  0.423077
49 -0.676471  0.297297
16  2.818182 -0.437500

In [88]:
#20
# Used to read a filef.read_csv
#dfread_csv

In [90]:
'''
 20 in built methods in numpy 


'''

'\n 20 in built methods in numpy \n\n\n'

In [91]:
import pandas as pd
import numpy as np

In [102]:
#1
#arange- used to get evenly spaced values within a given interval that doesnt include the last value value by default
#(start,stop-1)
arr = np.arange(0,10)

In [103]:
#2
#Generate arrays of zeros 
np.zeros(4)

array([0., 0., 0., 0.])

In [104]:
#3
#Generate arrays of ones
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [105]:
#4
#Return evenly spaced numbers over a specified interval.
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [106]:
#5
#Creates an identity matrix
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [107]:
#6
#Create an array of the given shape and populate it with random samples from a uniform distribution over [0, 1)
np.random.rand(5,5)

array([[0.65374404, 0.22853011, 0.81491146, 0.39768627, 0.53371956],
       [0.08508919, 0.23706175, 0.57938883, 0.34069058, 0.62816608],
       [0.42828568, 0.16063876, 0.30377144, 0.52818706, 0.68181342],
       [0.15729024, 0.93469382, 0.62001799, 0.82685995, 0.04604119],
       [0.13132092, 0.89654016, 0.63613865, 0.86190593, 0.56604131]])

In [108]:
#7
#Return random integers from low (inclusive) to high (exclusive)
np.random.randint(1,100,10)

array([ 1,  2,  2,  1, 50, 49, 94, 64, 20,  8])

In [109]:
#8
#Returns an array containing the same data with a new shape.
arr.reshape(2, 5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [110]:
#9
#MIN,MAX, ARGMAX, ARGMIN-These are useful methods for finding max or min values. Or to find their index locations of the highest and lowest number using argmin or argmax
arr.max()

9

In [111]:
#10
arr.argmax()

9

In [112]:
#11
arr.argmin()

0

In [113]:
#12
arr.min()

0

In [114]:
#13
#To know the data type of the object in the array:
arr.dtype

dtype('int32')

In [115]:
#14
#To know the standard deviation
arr.std()

2.8722813232690143

In [116]:
#15
#Gives the natural logarithm 
np.log(arr)

C:\Users\doyin\AppData\Local\Temp/ipykernel_2644/4246396001.py:3: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [117]:
#16
#Gives the exponent of all values in a given array
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [118]:
#17
#Gives the positive square root of an array
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [119]:
#18
#Gives the trigonometric sine for all array elements
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [120]:
#19
#Return a sample (or samples) from the "standard normal" distribution. Unlike rand which is uniform
np.random.randn(2)


array([-0.33053578, -0.20682321])

In [121]:
#20
#To get a copy
arr_new = arr.copy() + 2

arr_new

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])